from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from .style import ThemeSpec, PaletteSpec, CoverStyle, SectionHeaderStyle, TableStyleVariant, CalloutStyleVariant, ImageStyleVariant, KpiStyleVariant, CardStyleVariant, DecorationSpec


@dataclass
class DesignSpecification:
    """
    High-level creative direction chosen by the design planner.
    Keeps the layout tree deterministic while allowing visual variation.
    """
    palette: PaletteSpec = field(default_factory=PaletteSpec)
    cover_style: CoverStyle = CoverStyle.CENTERED
    section_header_style: SectionHeaderStyle = SectionHeaderStyle.STANDARD
    heading_level_1_style: SectionHeaderStyle = SectionHeaderStyle.STANDARD
    heading_level_2_style: SectionHeaderStyle = SectionHeaderStyle.STANDARD
    heading_level_3_style: SectionHeaderStyle = SectionHeaderStyle.STANDARD
    table_style: TableStyleVariant = TableStyleVariant.CORPORATE
    callout_style: CalloutStyleVariant = CalloutStyleVariant.LEFT_BORDER
    image_style: ImageStyleVariant = ImageStyleVariant.FULL_WIDTH
    kpi_style: KpiStyleVariant = KpiStyleVariant.FLAT
    highlight_style: CardStyleVariant = CardStyleVariant.FLAT
    decoration: DecorationSpec = field(default_factory=DecorationSpec)

@dataclass
class LayoutNode:
    """
    A recursive node in the layout composition tree.
    Can represent containers (section, two_column) or leaf components
    (heading, paragraph, list, table, timeline, kpi_cards, highlight_cards, callout, image).
    """
    type: str
    children: List['LayoutNode'] = field(default_factory=list)        # Used by 'section'
    children_left: List['LayoutNode'] = field(default_factory=list)   # Used by 'two_column'
    children_right: List['LayoutNode'] = field(default_factory=list)  # Used by 'two_column'
    properties: Dict[str, Any] = field(default_factory=dict)
    block_index: Optional[int] = None


@dataclass
class LayoutSpecification:
    """
    The output specification generated by the Layout Designer (LLM).
    Instructs the composition engine on how to brand and format the PDF.
    """
    theme: ThemeSpec = field(default_factory=ThemeSpec)
    design: DesignSpecification = field(default_factory=DesignSpecification)
    has_cover_page: bool = False
    page_numbers: bool = True
    margins: Dict[str, float] = field(default_factory=lambda: {"top": 2.0, "bottom": 2.0, "left": 2.0, "right": 2.0})  # Margin values in cm
    sections: List[LayoutNode] = field(default_factory=list)  # Root LayoutNodes of type 'section'
